### ISSUE TITLE
Support für Fluent Builder

### ISSUE THREAD

**Issue by beckerjohannes** [4Soft-de/jaxb-enhanced-navigation#41]
## General Troubleshooting

- [X] I have checked for similar questions / issues.
- [X] I have updated to the [latest version](https://mvnrepository.com/artifact/com.foursoft.jaxb2).

## Feature Request

https://mklemm.github.io/jaxb2-rich-contract-plugin/fluent-builder.html supports generation of fluent builders. This would be very useful for KBL & VEC Api Testing. However, the plugin does not work smoothly with our Typesafe-IDREFS.

A fork should be integrated here.

**Comment by gong4soft** [comment]
Hey, Any updates of this issue?

**Comment by DManstrator** [comment]
Closed due to archiving, see the ReadMe.
